// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVv-SD6vPxWzWVASvHmw-CDwX8eI0Dc4',
    appId: '1:847730488414:web:4acf38e31b240e35cbb0cf',
    messagingSenderId: '847730488414',
    projectId: 'friendly-eats-80c8a',
    authDomain: 'friendly-eats-80c8a.firebaseapp.com',
    storageBucket: 'friendly-eats-80c8a.appspot.com',
    measurementId: 'G-RCNST7CP5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuCdoEn3UCVXBG88khOSp36EY2jiIq-A',
    appId: '1:847730488414:android:fbd86ae82a306712cbb0cf',
    messagingSenderId: '847730488414',
    projectId: 'friendly-eats-80c8a',
    storageBucket: 'friendly-eats-80c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsz-m0uZn97BG-y_Ne-ngS2FV7IZCFZ8',
    appId: '1:847730488414:ios:b66ba425d7eee328cbb0cf',
    messagingSenderId: '847730488414',
    projectId: 'friendly-eats-80c8a',
    storageBucket: 'friendly-eats-80c8a.appspot.com',
    iosClientId: '847730488414-6vvl21kv3rs98s2k67qp0f5r2he269sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwsz-m0uZn97BG-y_Ne-ngS2FV7IZCFZ8',
    appId: '1:847730488414:ios:b66ba425d7eee328cbb0cf',
    messagingSenderId: '847730488414',
    projectId: 'friendly-eats-80c8a',
    storageBucket: 'friendly-eats-80c8a.appspot.com',
    iosClientId: '847730488414-6vvl21kv3rs98s2k67qp0f5r2he269sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
